[package]
name = "ic-registry-subnet-features"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.8.1"
ic-protobuf = { path = "../../protobuf" }
ic-ic00-types = { path = "../../types/ic00_types" }
serde = { version = "1.0.99", features = [ "derive" ] }
