[package]
name = "ic-registry-client-fake"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-types = { path = "../../types/types" }
