[package]
name = "ic-icrc1-index"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "Index canister for the ICRC1 Ledger"
edition = "2018"

[dependencies]
async-trait = "0.1.53"
candid = "0.8.1"
ciborium = "0.2"
dfn_core = { path = "../../../rust_canisters/dfn_core" }
dfn_http_metrics = { path = "../../../rust_canisters/dfn_http_metrics" }
ic-base-types = { path = "../../../types/base_types" }
ic-cdk = "0.6.0"
ic-cdk-macros = "0.6.0"
ic-icrc1 = { path = "../" }
ic-icrc1-ledger = { path = "../ledger" }
ic-metrics-encoder = { path = "../../../monitoring/metrics_encoder" }
num-traits = "0.2.14"
serde = "1.0.139"

[dev-dependencies]
candid = "0.8.1"
ic-base-types = { path = "../../../types/base_types" }
ic-icrc1 = { path = "../" }
ic-icrc1-ledger = { path = "../ledger" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
ic-ledger-core = { path = "../../ledger_core" }
ic-ledger-canister-core = { path = "../../ledger_canister_core" }
num-traits = "0.2.14"
proptest = "1.0"
serde_json = "1.0.54"

[[bin]]
name = "ic-icrc1-index"
path = "src/main.rs"
