[package]
name = "ic-prober"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-canister-client = { path = "../../canister_client" }
ic-metrics = { path = "../metrics" }
ic-types = { path = "../../types/types" }
lazy_static = "1.4.0"
prometheus = { version = "0.12.0", features = [ "process" ] }
rand = "0.8"
rand_chacha = "0.3"
reqwest = { version = "0.11.1", features = [ "native-tls" ] }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
slog-term = "2.6.0"
tiny_http = "0.10.0"
tokio = { version = "1.15.0", features = ["full"] }
url = "2.1.1"

[[bin]]
name = "ic-prober"
path = "src/main.rs"
