[package]
name = "ic-crypto-internal-basic-sig-ecdsa-secp256k1"
version = "0.8.0"
edition = "2021"

[dependencies]
base64 = "0.11.0"
hex = "0.4.2"
ic-crypto-internal-types = { path = "../../../crypto_lib/types" }
ic-crypto-secrets-containers = { path = "../../../../secrets_containers" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
ic-types = { path = "../../../../../types/types" }
openssl = "0.10.29"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }
simple_asn1 = "0.6.1"

[dev-dependencies]
ic-crypto-internal-test-vectors = { path = "../../../test_vectors" }
proptest = "1.0"
proptest-derive = "0.3.0"
regex = "1.5"
strum = "0.23.0"
wycheproof = "0.4"
