[package]
name = "ic-icrc1-agent"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "ICRC-1 compliant agent library."
edition = "2021"

[dependencies]
candid = "0.8.1"
garcon = { version = "0.2", features = ["async"] }
ic-agent = "=0.21.0"
ic-icrc1 = { path = "../" }
ic-ledger-core = { path = "../../ledger_core" }
num-traits = "0.2.14"
