[package]
name = "ic-crypto-internal-threshold-sig-bls12381"
version = "0.8.0"
edition = "2021"

[dependencies]
arrayvec = "0.5.1"
base64 = "0.11.0"
hex = "0.4"
ic-crypto-internal-bls12-381-type = { path = "../../bls12_381/type" }
ic-crypto-internal-seed = { path = "../../seed" }
ic-crypto-internal-threshold-sig-bls12381-der = { path = "der_utils"}
ic-crypto-internal-types = { path = "../../types" }
ic-crypto-sha = { path = "../../../../sha" }
ic-types = { path = "../../../../../types/types" }
lazy_static = "1.4.0"
rand = "0.8"
rand_chacha = "0.3"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
serde_cbor = "0.11.1"
strum_macros = "0.23.0"
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
proptest = "1.0"
proptest-derive = "0.3.0"

[[bench]]
name = "zk"
harness = false
