[package]
name = "ic-crypto-utils-threshold-sig-der"
version = "0.8.0"
edition = "2021"
description = "Utils for serializing threshold signatures to DER"

[dependencies]
base64 = "0.11.0"
ic-crypto-internal-threshold-sig-bls12381-der = { path = "../../internal/crypto_lib/threshold_sig/bls12_381/der_utils" }
ic-crypto-internal-types = { path = "../../internal/crypto_lib/types/" }
ic-types = { path = "../../../types/types" }

# Note: keep this crate as light-weight as possible. In particular, do not add
# dependencies that make this crate (e.g., transitively) dependent on
# heavy-weight crates such as miracl_core.

[dev-dependencies]
hex = "0.4.2"
tempfile = "3.1.0"