[package]
name = "ic-crypto-prng"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-crypto-sha = { path = "../sha" }
ic-interfaces = { path = "../../interfaces" }
ic-types = { path = "../../types/types" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
rand = "0.8"
rand_chacha = "0.3"
strum = "0.23.0"
strum_macros = "0.23.0"
